### ISSUE TITLE
New version 2.4.2 cause some problems

### ISSUE THREAD

**Issue by nikhil19rathore99** [prizraksarvar/VoodooI2CFTE#3]
As this post is continuation of vodooi2c issue 
new version causes some problems
kext used :vodooi2c, vodooi2cFTE
problems: lagging cursor, cursor is not smooth, cursor is moving too fast even at slow speed,         
                  3 fingures with thumb for launchpad not working correctly

about device: Asus X556UQK
trackpad: FTE1001
graphics: intel hd 620

**Comment by prizraksarvar** [comment]
This repo longer not supported, I think you need try fix this issues in file `https://github.com/prizraksarvar/VoodooI2CFTE/blob/master/VoodooI2CFTE/VoodooI2CFTETouchpadDriver.cpp` in function `bool VoodooI2CFTETouchpadDriver::initDevice() `. I replace calculated touchpad values with constants matched to my laptop (it's was easier)

**Comment by nikhil19rathore99** [comment]
> This repo longer not supported, I think you need try fix this issues in file `https://github.com/prizraksarvar/VoodooI2CFTE/blob/master/VoodooI2CFTE/VoodooI2CFTETouchpadDriver.cpp` in function `bool VoodooI2CFTETouchpadDriver::initDevice() `. I replace calculated touchpad values with constants matched to my laptop (it's was easier)

can u do that one for me ??

**Comment by prizraksarvar** [comment]
Sorry I can't, I think you can try write to gitter chat ( https://gitter.im/alexandred/VoodooI2C ), https://voodooi2c.github.io/#Troubleshooting/Troubleshooting . They helped me there

**Comment by nikhil19rathore99** [comment]
> Sorry I can't, I think you can try write to gitter chat ( https://gitter.im/alexandred/VoodooI2C ), https://voodooi2c.github.io/#Troubleshooting/Troubleshooting . They helped me there

Actually i've tried many times on gitter but no one there helping me out

**Comment by nikhil19rathore99** [comment]
> Sorry I can't, I think you can try write to gitter chat ( https://gitter.im/alexandred/VoodooI2C ), https://voodooi2c.github.io/#Troubleshooting/Troubleshooting . They helped me there

please update vodooi2cfte sattelite ??

**Comment by prizraksarvar** [comment]
I'll try help to you. You have programmer skill? You build driver on your mac? Sorry, my english is bad, maybe conversation with you help me too

**Comment by prizraksarvar** [comment]
You have telegram/skype? Maybe we can write there

**Comment by prizraksarvar** [comment]
I don't know satelites very well, if you want continue, maybe it will take many attempts. I will made satellite. You'll try install, and record video with log, and will try again

**Comment by prizraksarvar** [comment]
you have problems only in new version?

**Comment by nikhil19rathore99** [comment]
> you have problems only in new version?

all versions
this is from the beginging i.e in catalina also someone from vodooi2c told me to changes from vodooi2chid is not ported to fte , he told me to port the changes from i2chid satalite to mine fte, u know how to port changes ??

**Comment by nikhil19rathore99** [comment]
> You have telegram/skype? Maybe we can write there

yes i have telegram, 7678166778

**Comment by nikhil19rathore99** [comment]
> I'll try help to you. You have programmer skill? You build driver on your mac? Sorry, my english is bad, maybe conversation with you help me too

Yes

**Comment by prizraksarvar** [comment]
> > You have telegram/skype? Maybe we can write there
> 
> yes i have telegram, ph. no : 7678166778
I can't find you, please add me https://t.me/sarvar_has

**Comment by kprinssu** [comment]
@prizraksarvar what is required are these changes in https://github.com/kprinssu/VoodooI2CELAN/commit/6897677af23c1e647760ebfb4e23af22883fc995.

Upstream changes in 2.4.1+ of VoodooI2C have broken the FTE satellite kext. @alexandred's fork of the FTE repo is not actively maintained, can you kindly incorporate the changes from Elan? I'll merge it into @alexandred's fork asap. Please ping me on Gitter (https://gitter.im/kprinssu) if you need any assistance.

**Comment by Goshin** [comment]
Seems there are some changes left out.

https://github.com/prizraksarvar/VoodooI2CFTE/blob/6043891b989def5d0e7878049a8753e4dddeed44/VoodooI2CFTE/VoodooI2CFTETouchpadDriver.cpp#L146-L159

https://github.com/VoodooI2C/VoodooI2CELAN/commit/6897677af23c1e647760ebfb4e23af22883fc995#diff-8281f1285490da5d81881b110b72ba94L160-L169

```diff
-   read_in_progress = true;
-   thread_t new_thread;
-   kern_return_t ret = kernel_thread_start(OSMemberFunctionCast(thread_continue_t, this, &VoodooI2CELANTouchpadDriver::handle_input_threaded), this, &new_thread);
-   if (ret != KERN_SUCCESS) {
-       read_in_progress = false;
-       IOLog("%s::%s Thread error while attemping to get input report\n", getName(), device_name);
-   } else {
-       thread_deallocate(new_thread);
-   }
+   command_gate->attemptAction(OSMemberFunctionCast(IOCommandGate::Action, this, &VoodooI2CELANTouchpadDriver::parse_ELAN_report));
}
```

**Comment by prizraksarvar** [comment]
Thanks! I fixed this Issues, and made pull request to main repo
